blank_issues_enabled: false
# contact_links:
#   - name: Support question
#     url: 'discord server'
#     about: 'This repository is only for reporting bugs. If you need help using the library, click:'
